# Generated by Django 4.2.4 on 2023-08-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue_user_label_issue_assigned_to_issue_closed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AlterField(
            model_name='issue',
            name='github_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
