# Generated by Django 4.2.4 on 2023-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_url_alter_issue_github_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
