# Generated by Django 4.2.4 on 2023-08-24 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_github_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('github_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='label',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(to='api.label'),
        ),
        migrations.AddField(
            model_name='label',
            name='github_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='url',
            field=models.URLField(default='test_url', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_issues', to='api.githubuser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_issue', to='api.githubuser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_issue', to='api.githubuser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_issue', to='api.githubuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
